[2023-10-20 23:23:25,585] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.tercera_tarea scheduled__2023-08-16T00:00:00+00:00 [queued]>
[2023-10-20 23:23:25,606] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.tercera_tarea scheduled__2023-08-16T00:00:00+00:00 [queued]>
[2023-10-20 23:23:25,607] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-20 23:23:25,607] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-10-20 23:23:25,608] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-20 23:23:25,632] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): tercera_tarea> on 2023-08-16 00:00:00+00:00
[2023-10-20 23:23:25,638] {standard_task_runner.py:52} INFO - Started process 3738 to run task
[2023-10-20 23:23:25,643] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'tercera_tarea', 'scheduled__2023-08-16T00:00:00+00:00', '--job-id', '1147', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmp9mqckneh', '--error-file', '/tmp/tmp1dxep_cn']
[2023-10-20 23:23:25,646] {standard_task_runner.py:80} INFO - Job 1147: Subtask tercera_tarea
[2023-10-20 23:23:25,769] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.tercera_tarea scheduled__2023-08-16T00:00:00+00:00 [running]> on host dfdda228c9fc
[2023-10-20 23:23:25,797] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2023-10-20 23:23:25,803] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 3738. PIDs of all processes in the group: [3738]
[2023-10-20 23:23:25,808] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 3738
[2023-10-20 23:23:25,835] {process_utils.py:75} INFO - Process psutil.Process(pid=3738, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='23:23:25') (3738) terminated with exit code Negsignal.SIGTERM
[2023-10-20 23:23:25,838] {local_task_job.py:156} INFO - Task exited with return code 143
[2023-10-20 23:23:25,890] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=mi_primer_dag_v3, task_id=tercera_tarea, execution_date=20230816T000000, start_date=20231020T232325, end_date=20231020T232325
[2023-10-20 23:23:25,968] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
