[2023-10-20 23:23:25,587] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.primera_tarea scheduled__2023-08-21T00:00:00+00:00 [queued]>
[2023-10-20 23:23:25,605] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: mi_primer_dag_v3.primera_tarea scheduled__2023-08-21T00:00:00+00:00 [queued]>
[2023-10-20 23:23:25,606] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-20 23:23:25,607] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-10-20 23:23:25,607] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-20 23:23:25,630] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): primera_tarea> on 2023-08-21 00:00:00+00:00
[2023-10-20 23:23:25,635] {standard_task_runner.py:52} INFO - Started process 3737 to run task
[2023-10-20 23:23:25,640] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'mi_primer_dag_v3', 'primera_tarea', 'scheduled__2023-08-21T00:00:00+00:00', '--job-id', '1149', '--raw', '--subdir', 'DAGS_FOLDER/primer_dag_v3.py', '--cfg-path', '/tmp/tmpnpdv8v28', '--error-file', '/tmp/tmpoenaon2w']
[2023-10-20 23:23:25,642] {standard_task_runner.py:80} INFO - Job 1149: Subtask primera_tarea
[2023-10-20 23:23:25,763] {task_command.py:371} INFO - Running <TaskInstance: mi_primer_dag_v3.primera_tarea scheduled__2023-08-21T00:00:00+00:00 [running]> on host dfdda228c9fc
[2023-10-20 23:23:25,798] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2023-10-20 23:23:25,807] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 3737. PIDs of all processes in the group: [3737]
[2023-10-20 23:23:25,808] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 3737
[2023-10-20 23:23:25,873] {process_utils.py:75} INFO - Process psutil.Process(pid=3737, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='23:23:25') (3737) terminated with exit code Negsignal.SIGTERM
[2023-10-20 23:23:25,874] {local_task_job.py:156} INFO - Task exited with return code 143
[2023-10-20 23:23:25,946] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=mi_primer_dag_v3, task_id=primera_tarea, execution_date=20230821T000000, start_date=20231020T232325, end_date=20231020T232325
[2023-10-20 23:23:26,016] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
