[2023-10-29 22:03:19,589] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: rent_analysis_test.rent_analysis_etl manual__2023-10-29T17:10:02.641675+00:00 [queued]>
[2023-10-29 22:03:19,611] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: rent_analysis_test.rent_analysis_etl manual__2023-10-29T17:10:02.641675+00:00 [queued]>
[2023-10-29 22:03:19,613] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-10-29 22:03:19,615] {taskinstance.py:1377} INFO - Starting attempt 13 of 13
[2023-10-29 22:03:19,617] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-10-29 22:03:19,649] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): rent_analysis_etl> on 2023-10-29 17:10:02.641675+00:00
[2023-10-29 22:03:19,655] {standard_task_runner.py:52} INFO - Started process 2116 to run task
[2023-10-29 22:03:19,660] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'rent_analysis_test', 'rent_analysis_etl', 'manual__2023-10-29T17:10:02.641675+00:00', '--job-id', '2045', '--raw', '--subdir', 'DAGS_FOLDER/rent_analysis_dag.py', '--cfg-path', '/tmp/tmp_gsii7t9', '--error-file', '/tmp/tmph10tbrg6']
[2023-10-29 22:03:19,663] {standard_task_runner.py:80} INFO - Job 2045: Subtask rent_analysis_etl
[2023-10-29 22:03:19,759] {task_command.py:371} INFO - Running <TaskInstance: rent_analysis_test.rent_analysis_etl manual__2023-10-29T17:10:02.641675+00:00 [running]> on host 116fb122d054
[2023-10-29 22:03:19,858] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=rent_analysis_test
AIRFLOW_CTX_TASK_ID=rent_analysis_etl
AIRFLOW_CTX_EXECUTION_DATE=2023-10-29T17:10:02.641675+00:00
AIRFLOW_CTX_TRY_NUMBER=13
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-29T17:10:02.641675+00:00
[2023-10-29 22:03:20,338] {logging_mixin.py:115} INFO - Loading data to Redshift
[2023-10-29 22:03:20,341] {logging_mixin.py:115} INFO - data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com 5439 data-engineer-database jbrekesdata_coderhouse qHVZ6LI393
[2023-10-29 22:03:20,343] {logging_mixin.py:115} INFO - Connecting to Redshift Cluster
[2023-10-29 22:03:20,629] {logging_mixin.py:115} INFO - Failed to connect to Redshift: an integer is required (got type str)
[2023-10-29 22:03:20,633] {logging_mixin.py:115} INFO - Connection Complete
[2023-10-29 22:03:20,634] {logging_mixin.py:115} INFO - Failed to create Engine: local variable 'conn' referenced before assignment
[2023-10-29 22:03:20,636] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rent_analysis_functions/functions.py", line 351, in etl_process
    conn, engine = redshift_connection(host, port, database, user, password)
TypeError: cannot unpack non-iterable NoneType object
[2023-10-29 22:03:20,650] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=rent_analysis_test, task_id=rent_analysis_etl, execution_date=20231029T171002, start_date=20231029T220319, end_date=20231029T220320
[2023-10-29 22:03:20,669] {standard_task_runner.py:97} ERROR - Failed to execute job 2045 for task rent_analysis_etl (cannot unpack non-iterable NoneType object; 2116)
[2023-10-29 22:03:20,680] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-10-29 22:03:20,717] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
